//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaintShopProFiletype.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PaintShopProFiletype.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LZ77.
        /// </summary>
        internal static string CompressionFormatLZ77Text {
            get {
                return ResourceManager.GetString("CompressionFormatLZ77Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string CompressionFormatNoneText {
            get {
                return ResourceManager.GetString("CompressionFormatNoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RLE.
        /// </summary>
        internal static string CompressionFormatRLEText {
            get {
                return ResourceManager.GetString("CompressionFormatRLEText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression Format.
        /// </summary>
        internal static string CompressionFormatText {
            get {
                return ResourceManager.GetString("CompressionFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Version.
        /// </summary>
        internal static string FileVersionText {
            get {
                return ResourceManager.GetString("FileVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file width and height must be greater than zero..
        /// </summary>
        internal static string InvalidDocumentDimensions {
            get {
                return ResourceManager.GetString("InvalidDocumentDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Paint Shop Pro File..
        /// </summary>
        internal static string InvalidPSPFile {
            get {
                return ResourceManager.GetString("InvalidPSPFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected Paint Shop Pro format supports a maximum of {0} layers..
        /// </summary>
        internal static string MaxLayersFormat {
            get {
                return ResourceManager.GetString("MaxLayersFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file does not contain any Raster layers..
        /// </summary>
        internal static string RasterLayerNotFound {
            get {
                return ResourceManager.GetString("RasterLayerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a supported bit depth..
        /// </summary>
        internal static string UnsupportedBitDepth {
            get {
                return ResourceManager.GetString("UnsupportedBitDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paint Shop Pro 5.
        /// </summary>
        internal static string Version5 {
            get {
                return ResourceManager.GetString("Version5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paint Shop Pro 6, 7, 8, 9.
        /// </summary>
        internal static string Version6AndLater {
            get {
                return ResourceManager.GetString("Version6AndLater", resourceCulture);
            }
        }
    }
}
